export const UNDEFINED = "undefined"
export const MANAGE_ACCOUNTS = "MANAGE_ACCOUNTS"
export const MANAGE_BOOKS = "MANAGE_BOOKS"
export const RETURN_BOOKS = "RETURN_BOOKS"
export const ROLE_ADMIN = "admin"
export const ROLE_LIBRARIAN = "librarian"
export const DEFAULT_IMG = "/imgDefault.png"
export const DEFAULT_BOOK_IMG = "/bookImgDefault.png"
