export const LOGIN = "/login"
export const ACCOUNT_DETAIL = "/users/:id"
export const ACCOUNT_NEW = "/new/user"
export const ACCOUNT_LIST = "/users"
export const BOOKS_RETURN = "/return/books"
export const BOOK_LIST = "/books"
export const BOOK_DETAIL = "/books/:id"
